### ISSUE TITLE
不错 支持一下

### ISSUE THREAD

**Issue by DiamondYuan** [Dounx/NintendoSwitchEShopHelper#1]
虽然不是安卓开发者。不过作为服务端开发者，方便了好多。

**Comment by Dounx** [comment]
我觉得其实像这种爬虫还是用服务器爬完后再发给App比较好……，总之多谢支持～

**Comment by DiamondYuan** [comment]
我是爬虫把psn的游戏全部爬完存数据库了。准备有空封装一下你的代码。也存数据库里

**Comment by Dounx** [comment]
那你在做价格抓取的时候不要像我这样写，一次可以查询一个国家50个游戏的价格数据
